# Generated by Django 4.0.2 on 2022-03-01 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='answer',
            new_name='ans',
        ),
    ]
