# Generated by Django 4.0.2 on 2022-03-01 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_rename_ans_quesmodel_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quesmodel',
            old_name='questions',
            new_name='question',
        ),
    ]
